const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'../..');
const output=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'uhv-ui-'));
(async()=>{
  const browser=await chromium.launch({headless:true,...(process.env.UHV_CHROMIUM_BIN?{executablePath:process.env.UHV_CHROMIUM_BIN,args:['--no-sandbox']}:{} )});
  const context=await browser.newContext({viewport:{width:1360,height:980},deviceScaleFactor:1});
  const page=await context.newPage();
  const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  await page.goto('file://'+root+'/UHVChamberBuilder/ui/index.html');
  await page.waitForFunction(()=>document.querySelectorAll('.ports-table tbody tr[data-row-id]').length===3);
  let checks=0;
  assert.equal(await page.locator('#points tbody tr').count(),1);checks++;
  assert.equal(await page.locator('.ports-table input[data-field="override.od"]').first().getAttribute('readonly'),'');checks++;
  await page.screenshot({path:output+'/qa_light.png',fullPage:true});
  await page.locator('[data-page="about"]').click();
  assert.equal(await page.locator('#about-version').innerText(),'1.3.1');checks++;
  assert.equal(await page.locator('#page-about img').evaluate(img=>img.complete&&img.naturalWidth>0),true);checks++;
  assert.match(await page.locator('#page-about').innerText(),/Amon P. Lanz/);checks++;
  await page.screenshot({path:output+'/qa_about_light.png',fullPage:true});
  await page.locator('[data-copy-citation="text"]').click();
  await page.waitForFunction(()=>document.querySelector('#copy-status').textContent.includes('Text selected'));
  assert.equal(await page.locator('#citation-text').evaluate(el=>el.selectionEnd-el.selectionStart),await page.locator('#citation-text').evaluate(el=>el.value.length));checks++;
  assert.match(await page.locator('#citation-text').inputValue(),/https:\/\/github.com\/AmLanz\/UHV-Chamber-Builder/);checks++;
  await page.locator('[data-page="defaults"]').click();
  const gasketOffset=page.locator('input[data-scope="defaults"][data-field="gasket_standoff"]');
  assert.match(await gasketOffset.locator('..').innerText(),/outer-face offset/);checks++;
  await gasketOffset.fill('-0.5');await gasketOffset.press('Tab');
  assert.equal(await gasketOffset.inputValue(),'-0.5');checks++;
  await page.locator('input[data-scope="flange-default"][data-id="DN40CF"][data-field="od"]').fill('72');
  await page.locator('input[data-scope="flange-default"][data-id="DN40CF"][data-field="od"]').press('Tab');
  await page.locator('[data-page="chamber"]').click();
  assert.equal(await page.locator('.ports-table input[data-field="override.od"]').nth(1).inputValue(),'72');checks++;
  await page.locator('.ports-table input[data-field="deviate"]').nth(1).check();
  const override=page.locator('.ports-table input[data-field="override.od"]').nth(1);
  assert.equal(await override.getAttribute('readonly'),null);checks++;
  await override.fill('73');await override.press('Tab');
  await page.locator('[data-page="defaults"]').click();
  await page.locator('input[data-scope="flange-default"][data-id="DN40CF"][data-field="od"]').fill('74');
  await page.locator('input[data-scope="flange-default"][data-id="DN40CF"][data-field="od"]').press('Tab');
  await page.locator('[data-action="theme"]').click();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');checks++;
  await page.screenshot({path:output+'/qa_defaults_dark.png',fullPage:true});
  await page.locator('[data-page="about"]').click();
  await page.locator('.about-details summary').click();
  await page.screenshot({path:output+'/qa_about_dark.png',fullPage:true});
  await page.locator('[data-page="chamber"]').click();
  assert.equal(await override.inputValue(),'73');checks++;
  assert.equal(await page.locator('.ports-table input[data-field="override.od"]').nth(2).inputValue(),'74');checks++;
  await page.locator('.ports-table select[data-field="configuration"]').first().selectOption('rotatable');
  await page.locator('.ports-table [data-action="expand"]').first().click();
  assert.match(await page.locator('.ports-table .details-row').innerText(),/Two schematic/);checks++;
  await page.locator('[data-action="add-point"]').click();
  assert.equal(await page.locator('#points input[data-field="name"]').nth(1).inputValue(),'B');checks++;
  const pointB=await page.locator('#points input[data-field="name"]').nth(1).getAttribute('data-id');
  await page.locator('.ports-table select[data-field="point"]').first().selectOption(pointB);
  await page.locator('#points [data-action="delete-row"]').nth(1).click();
  assert.equal(await page.locator('.ports-table tr.invalid[data-row-id]').count(),1);checks++;
  const pointA=await page.locator('#points input[data-field="name"]').first().getAttribute('data-id');
  await page.locator('.ports-table select[data-field="point"]').first().selectOption(pointA);
  assert.equal(await page.locator('.ports-table tr.invalid[data-row-id]').count(),0);checks++;
  await page.locator('#new-body-kind').selectOption('tube');await page.locator('[data-action="add-body"]').click();
  await page.locator('#bodies select[data-field="end_plus"]').selectOption('flange');
  assert.equal(await page.locator('.ports-table tbody tr[data-row-id]').count(),4);checks++;
  assert.equal(await page.locator('.ports-table select[data-field="preset"]').last().inputValue(),'DN200CF');checks++;
  assert.equal(await page.locator('.ports-table input[data-field="number"]').last().inputValue(),'');checks++;
  await page.locator('#bodies select[data-field="end_plus"]').selectOption('open');
  assert.equal(await page.locator('.ports-table tbody tr[data-row-id]').count(),3);checks++;
  await page.screenshot({path:output+'/qa_dark.png',fullPage:true});
  const contrastForTheme=async()=>await page.evaluate(()=>{
    const css=getComputedStyle(document.documentElement);
    function rgb(v){const s=css.getPropertyValue('--'+v).trim().slice(1);return (s.length===3?s.split('').map(c=>c+c).join(''):s).match(/../g).map(x=>parseInt(x,16)/255);}
    function l(v){return rgb(v).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4).reduce((a,x,i)=>a+x*[.2126,.7152,.0722][i],0);}
    return ['text/surface','muted/readonly','muted/raised','accenttext/accent','red/redbg','amber/amberbg','blue/bluebg'].map(s=>{const[a,b]=s.split('/'),x=l(a),y=l(b);return{pair:s,ratio:(Math.max(x,y)+.05)/(Math.min(x,y)+.05)}});
  });
  const contrast={dark:await contrastForTheme()};
  await page.locator('[data-page="defaults"]').click();await page.locator('[data-action="theme"]').click();
  contrast.light=await contrastForTheme();
  assert.ok([...contrast.light,...contrast.dark].every(x=>x.ratio>=4.5),JSON.stringify(contrast));checks++;
  await page.locator('[data-page="chamber"]').click();
  await page.setViewportSize({width:900,height:850});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks++;
  await page.locator('[data-action="preview"]').first().click();
  assert.match(await page.locator('#notice').innerText(),/interface preview/i);checks++;
  assert.deepEqual(errors,[]);checks++;
  assert.equal(await page.locator('[data-action="section"], [data-action="new_hybrid"]').count(),0);checks++;
  const portIds=await page.locator('.ports-table tr[data-row-id]').evaluateAll(rows=>rows.map(r=>r.dataset.rowId));
  for(const [i,n] of ['10','2','5'].entries()){
    const input=page.locator('.ports-table input[data-field="number"]').nth(i);await input.fill(n);await input.press('Tab');
  }
  await page.locator('.ports-table [data-action="duplicate"]').first().click();
  let currentIds=await page.locator('.ports-table tr[data-row-id]').evaluateAll(rows=>rows.map(r=>r.dataset.rowId));
  assert.deepEqual([currentIds[0],...currentIds.slice(2)],portIds);checks++;
  assert.equal(await page.locator('.ports-table input[data-field="number"]').nth(1).inputValue(),'');checks++;
  assert.match(await page.locator('.ports-table input[data-field="name"]').nth(1).inputValue(),/copy$/);checks++;
  await page.locator('.ports-table [data-action="move-up"]').nth(1).click();
  assert.equal(await page.locator('.ports-table tr[data-row-id]').first().getAttribute('data-row-id'),currentIds[1]);checks++;
  await page.locator('.ports-table [data-action="move-down"]').first().click();
  assert.equal(await page.locator('.ports-table tr[data-row-id]').first().getAttribute('data-row-id'),portIds[0]);checks++;
  await page.locator('[data-action="add-port"]').click();
  assert.equal(await page.locator('.ports-table input[data-field="number"]').last().inputValue(),'');checks++;
  await page.locator('.ports-table input[data-field="name"]').last().fill('Alpha');
  await page.locator('[data-action="sort-ports"]').click();
  assert.deepEqual(await page.locator('.ports-table input[data-field="number"]').evaluateAll(inputs=>inputs.map(x=>x.value)),['2','5','10','','']);checks++;
  assert.deepEqual(await page.locator('.ports-table input[data-field="name"]').evaluateAll(inputs=>inputs.slice(-2).map(x=>x.value)),['Alpha','Pump copy']);checks++;
  assert.equal(await page.locator('.ports-table [data-action="move-up"]').first().isDisabled(),true);checks++;
  assert.equal(await page.locator('.ports-table [data-action="move-down"]').last().isDisabled(),true);checks++;
  const bridge=await page.context().newPage();
  bridge.on('pageerror',e=>errors.push(e.message));
  await bridge.addInitScript(()=>{
    window.calls=[];window.hostKey='mock-document';window.hostAvailable=true;window.hostBusy=false;
    window.adsk={fusionSendData:async(action,raw)=>{
      const data=JSON.parse(raw);window.calls.push({action,data});
      if(action==='copy_text')return JSON.stringify({ok:true,result:{copied:!window.clipboardFail}});
      if(window.hostBusy)return JSON.stringify({ok:false,code:'busy',error:'Operation active'});
      if(action==='save'&&window.holdNextSave){window.holdNextSave=false;return new Promise(resolve=>{window.releaseSave=()=>resolve(JSON.stringify({ok:true,result:{doc_key:data.doc_key}}));});}
      if(action!=='bootstrap'&&data.doc_key!==window.hostKey)return JSON.stringify({ok:false,code:'document_changed',error:'Refreshing'});
      const recipe=JSON.parse(JSON.stringify(window.UHV_DEMO.recipe));recipe.name=window.hostKey+' chamber';
      const result=action==='bootstrap'?(window.hostAvailable?{available:true,recipe,catalog:window.UHV_DEMO.catalog,doc_key:window.hostKey,document:window.hostKey,build_context:{allowed:true},statuses:{}}:{available:false,doc_key:'',document:'No open design',message:'Open a Fusion design to edit a chamber.'}):{doc_key:window.hostKey,...(['build','preview'].includes(action)?{queued:true}:{})};
      return JSON.stringify({ok:true,result});
    }};
  });
  await bridge.goto('file://'+root+'/UHVChamberBuilder/ui/index.html');
  await bridge.locator('.ports-table input[data-field="azimuth"]').first().fill('-75');
  await bridge.locator('.ports-table input[data-field="azimuth"]').nth(1).fill('75');
  await bridge.locator('.ports-table input[data-field="elevation"]').first().fill('15');
  await bridge.locator('.primarybar [data-action="build"]').click();
  assert.deepEqual(await bridge.evaluate(()=>{const p=window.calls.find(x=>x.action==='build').data.recipe.ports;return [p[0].azimuth,p[1].azimuth,p[0].elevation];}),['-75','75','15']);checks++;
  assert.equal(await bridge.locator('#chamber-name').isDisabled(),true);checks++;
  assert.equal(await bridge.evaluate(()=>window.calls.find(x=>x.action==='build').data.doc_key),'mock-document');checks++;
  await bridge.evaluate(()=>window.fusionJavaScriptHandler.handle('completed',JSON.stringify({message:'Mock build completed'})));
  await bridge.waitForFunction(()=>!document.querySelector('#chamber-name').disabled);
  assert.equal(await bridge.locator('#chamber-name').isDisabled(),false);checks++;
  assert.match(await bridge.locator('#notice').innerText(),/Mock build completed/);checks++;
  await bridge.locator('[data-page="about"]').click();
  await bridge.locator('[data-copy-citation="text"]').click();
  await bridge.waitForFunction(()=>document.querySelector('#copy-status').textContent==='Citation copied.');
  assert.equal(await bridge.evaluate(()=>Object.hasOwn(window.calls.at(-1).data,'recipe')),false);checks++;
  assert.match(await bridge.evaluate(()=>window.calls.at(-1).data.text),/version 1\.3\.1/);checks++;
  await bridge.locator('[data-copy-citation="bibtex"]').click();
  await bridge.waitForFunction(()=>document.querySelector('#copy-status').textContent==='BibTeX copied.');
  assert.equal((await bridge.evaluate(()=>window.calls.at(-1).data.text)).trim(),fs.readFileSync(root+'/UHVChamberBuilder/CITATION.bib','utf8').trim());checks++;
  await bridge.evaluate(()=>{window.clipboardFail=true;});
  await bridge.locator('[data-copy-citation="text"]').click();
  await bridge.waitForFunction(()=>document.querySelector('#copy-status').textContent.includes('Text selected'));
  assert.equal(await bridge.locator('#citation-text').evaluate(el=>el.selectionEnd-el.selectionStart),await bridge.locator('#citation-text').evaluate(el=>el.value.length));checks++;
  await bridge.evaluate(()=>{window.clipboardFail=false;});
  await bridge.locator('[data-page="chamber"]').click();
  assert.equal(await bridge.locator('#flange-angle-mode').count(),0);checks++;
  assert.match(await bridge.locator('.ports-table thead').innerText(),/Azimuth °.*Elevation °/);checks++;
  assert.equal(await bridge.locator('#flange-angle-note').innerText(),'Azimuth: angle from +X (negative selects the opposite Y half). Elevation: rotation around X, positive toward +Z on either half.');checks++;
  assert.equal(await bridge.locator('.card:has(#ports) .card-note').first().innerText(),'Enter flange numbers manually; skipped numbers are allowed. ↑ / ↓ move rows. Distance starts at referenced point and ends at the outer mating face.');checks++;
  assert.deepEqual(await bridge.locator('.ports-table input[data-field="azimuth"]').evaluateAll(xs=>xs.slice(0,2).map(x=>x.value)),['-75','75']);checks++;
  assert.equal(await bridge.locator('.ports-table input[data-field="elevation"]').first().inputValue(),'15');checks++;
  await bridge.locator('#flange-angle-note').scrollIntoViewIfNeeded();
  await bridge.screenshot({path:output+'/qa_x_ring.png'});
  await bridge.setViewportSize({width:900,height:850});
  assert.ok(await bridge.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks++;
  await bridge.locator('#flange-angle-note').scrollIntoViewIfNeeded();
  await bridge.screenshot({path:output+'/qa_x_ring_narrow.png'});
  await bridge.locator('.ports-table input[data-field="distance"]').first().fill('240');
  await bridge.locator('.primarybar [data-action="build"]').click();
  assert.equal(await bridge.evaluate(()=>window.calls.filter(x=>x.action==='build').length),2);checks++;
  assert.equal(await bridge.evaluate(()=>window.calls.filter(x=>x.action==='build').at(-1).data.recipe.ports[0].distance),'240');checks++;
  assert.equal(await bridge.evaluate(()=>Object.hasOwn(window.calls.filter(x=>x.action==='build').at(-1).data.recipe.defaults,'flange_angle_mode')),false);checks++;
  await bridge.evaluate(()=>window.fusionJavaScriptHandler.handle('completed','{}'));
  await bridge.waitForFunction(()=>!document.querySelector('#chamber-name').disabled);
  await bridge.locator('.ports-table input[data-field="distance"]').first().fill('245');
  await bridge.locator('.ports-table [data-action="build"]').first().click();
  assert.equal(await bridge.evaluate(()=>window.calls.filter(x=>x.action==='build').length),3);checks++;
  await bridge.evaluate(()=>window.fusionJavaScriptHandler.handle('completed','{}'));
  await bridge.waitForFunction(()=>!document.querySelector('#chamber-name').disabled);
  const switchDocument=async key=>{
    await bridge.evaluate(key=>{window.hostKey=key;const before=window.calls.length;window.fusionJavaScriptHandler.handle('reload','{}');window.returnedBeforeRequest=before===window.calls.length;},key);
    await bridge.waitForFunction(key=>document.querySelector('#chamber-name').value===key+' chamber'&&!document.querySelector('#chamber-name').disabled,key);
  };
  await switchDocument('new-document');
  assert.match(await bridge.locator('.ports-table thead').innerText(),/Azimuth/);checks++;
  assert.equal(await bridge.evaluate(()=>window.returnedBeforeRequest),true);checks++;
  await bridge.locator('.primarybar [data-action="build"]').click();
  await bridge.evaluate(()=>window.fusionJavaScriptHandler.handle('completed',JSON.stringify({doc_key:'mock-document',message:'OLD RESULT'})));
  await bridge.waitForTimeout(30);
  assert.equal(await bridge.locator('#chamber-name').isDisabled(),true);checks++;
  assert.doesNotMatch(await bridge.locator('#notice').innerText(),/OLD RESULT/);checks++;
  await bridge.evaluate(()=>window.fusionJavaScriptHandler.handle('completed',JSON.stringify({doc_key:'new-document',message:'Current build completed'})));
  await bridge.waitForFunction(()=>!document.querySelector('#chamber-name').disabled);
  // A slow request must finish without applying its old document's result;
  // queued edits for that document must never reach the host.
  const validations=await bridge.evaluate(()=>window.calls.filter(x=>x.action==='validate').length);
  await bridge.evaluate(()=>{window.holdNextSave=true;window.oldSave=request('save').catch(e=>e.code);window.oldValidate=request('validate').catch(e=>e.code);});
  await bridge.waitForFunction(()=>typeof window.releaseSave==='function');
  await bridge.evaluate(()=>{window.hostKey='third-document';window.fusionJavaScriptHandler.handle('reload','{}');window.releaseSave();});
  await bridge.waitForFunction(()=>document.querySelector('#chamber-name').value==='third-document chamber'&&!document.querySelector('#chamber-name').disabled);
  assert.equal(await bridge.evaluate(()=>window.oldSave),'stale');checks++;
  assert.equal(await bridge.evaluate(()=>window.oldValidate),'stale');checks++;
  assert.equal(await bridge.evaluate(()=>window.calls.filter(x=>x.action==='validate').length),validations);checks++;
  await bridge.evaluate(()=>{window.hostBusy=true;window.fusionJavaScriptHandler.handle('reload','{}');});
  await bridge.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Waiting for Fusion'));
  assert.equal(await bridge.locator('#chamber-name').isDisabled(),true);checks++;
  await bridge.evaluate(()=>{window.hostBusy=false;});await switchDocument('fourth-document');
  assert.equal(await bridge.locator('#chamber-name').isDisabled(),false);checks++;
  await bridge.evaluate(()=>{window.hostAvailable=false;window.hostKey='';window.fusionJavaScriptHandler.handle('reload','{}');});
  await bridge.waitForFunction(()=>document.querySelector('#document').textContent==='No open design');
  assert.equal(await bridge.locator('#chamber-name').isDisabled(),true);checks++;
  assert.equal(await bridge.locator('[data-page="about"]').isEnabled(),true);checks++;
  await bridge.locator('[data-page="about"]').click();
  await bridge.locator('[data-copy-citation="text"]').click();
  await bridge.waitForFunction(()=>document.querySelector('#copy-status').textContent==='Citation copied.');
  assert.equal(await bridge.locator('#chamber-name').isDisabled(),true);checks++;
  await bridge.evaluate(()=>{window.hostAvailable=true;});await switchDocument('reopened-document');
  assert.equal(await bridge.locator('#chamber-name').isDisabled(),false);checks++;
  assert.deepEqual(errors,[]);checks++;
  fs.writeFileSync(output+'/qa_ui_results.json',JSON.stringify({checks,consoleErrors:errors,contrast},null,2));
  console.log(JSON.stringify({checks,consoleErrors:errors,contrast,output},null,2));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
